package:
  name: "sbxpy"
  version: "0.6.0"

source:
  git_url: "https://github.com/socobox/sbxcloudpython.git"

requirements:
  build:
    - python
    - setuptools
    - aiohttp

  run:
    - python

build:
  noarch: python
